from __future__ import annotations


ROUTE_REASON_CODES = [
    "OBJECTIVE_MATCH",
    "SOURCE_TRACE_PRESENT",
    "SOURCE_TRACE_MISSING",
    "METADATA_INCOMPLETE",
    "PERMISSION_SCOPE_UNKNOWN",
    "AUTH_CONTEXT_UNKNOWN",
    "USER_CONFIRMATION_REQUIRED",
    "ORG_POLICY_UNKNOWN",
    "PRIVACY_POLICY_MISSING",
    "DATA_RETENTION_MISSING",
    "PRICING_UNKNOWN",
    "STALE_METADATA",
    "VERSION_DRIFT",
    "RUGPULL_DIFF_SUSPECTED",
    "NEGATIVE_CACHE_HIT",
    "DESTRUCTIVE_ACTION",
    "EXTERNAL_SEND",
    "DATA_EGRESS",
    "SECRET_LIKE_INPUT",
    "CERTIFICATION_OVERCLAIM",
    "PRODUCT_READINESS_OVERCLAIM",
    "ACTION_AUTHORIZATION_OVERCLAIM",
    "TOOL_RISK_REQUIRES_AGENTSEC",
    "CODE_RELEASE_REQUIRES_QIRA",
    "DATA_USE_REQUIRES_DATACAPSULE",
    "HUMAN_APPROVAL_REQUIRED",
]


def is_reason_code(value: str) -> bool:
    return value in ROUTE_REASON_CODES


def reason_codes_for_route(route: str) -> list[str]:
    return {
        "ALLOW_DISCOVERY_ONLY": ["OBJECTIVE_MATCH", "SOURCE_TRACE_PRESENT"],
        "ALLOW_READ_ONLY": ["OBJECTIVE_MATCH", "SOURCE_TRACE_PRESENT"],
        "ALLOW_DRAFT_ONLY": ["OBJECTIVE_MATCH", "SOURCE_TRACE_PRESENT"],
        "ALLOW_LOW_RISK_CALL": ["OBJECTIVE_MATCH", "SOURCE_TRACE_PRESENT", "USER_CONFIRMATION_REQUIRED"],
        "HOLD_MISSING_FIELDS": ["METADATA_INCOMPLETE"],
        "HOLD_AUTHORIZATION": ["AUTH_CONTEXT_UNKNOWN", "USER_CONFIRMATION_REQUIRED"],
        "HOLD_SECURITY_REVIEW": ["TOOL_RISK_REQUIRES_AGENTSEC"],
        "HOLD_PRIVACY_REVIEW": ["PRIVACY_POLICY_MISSING", "DATA_USE_REQUIRES_DATACAPSULE"],
        "HOLD_POLICY_CLARITY": ["ORG_POLICY_UNKNOWN"],
        "HOLD_STALE_METADATA": ["STALE_METADATA"],
        "HOLD_RUGPULL_DIFF": ["VERSION_DRIFT", "RUGPULL_DIFF_SUSPECTED"],
        "HOLD_RATE_LIMIT_OR_COST": ["PRICING_UNKNOWN"],
        "HOLD_CONTEXT_AMBIGUITY": ["METADATA_INCOMPLETE"],
        "BLOCK_UNTRUSTED_SOURCE": ["SOURCE_TRACE_MISSING"],
        "BLOCK_DESTRUCTIVE_ACTION": ["DESTRUCTIVE_ACTION"],
        "BLOCK_SECRET_OR_PRIVATE_DATA": ["SECRET_LIKE_INPUT"],
        "BLOCK_CERTIFICATION_CLAIM": ["CERTIFICATION_OVERCLAIM"],
        "BLOCK_PRODUCT_READINESS_CLAIM": ["PRODUCT_READINESS_OVERCLAIM"],
        "BLOCK_ACTION_AUTHORIZATION_CLAIM": ["ACTION_AUTHORIZATION_OVERCLAIM"],
        "BLOCK_POLICY_FORBIDDEN": ["ORG_POLICY_UNKNOWN"],
        "ESCALATE_AGENTSEC": ["TOOL_RISK_REQUIRES_AGENTSEC"],
        "ESCALATE_QIRA": ["CODE_RELEASE_REQUIRES_QIRA"],
        "ESCALATE_DATACAPSULE": ["DATA_USE_REQUIRES_DATACAPSULE"],
        "ESCALATE_HUMAN_APPROVAL": ["HUMAN_APPROVAL_REQUIRED"],
        "ESCALATE_OPERATOR_POLICY": ["ORG_POLICY_UNKNOWN"],
    }.get(route, ["METADATA_INCOMPLETE"])
